version: '3.4'

services:
  postgres:
    image: postgres:15
    container_name: pg_container
    restart: unless-stopped
    volumes:
      - ./postgres/.psqlrc:/root/.psqlrc:ro
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/dumps:/dumps
      - ./postgres/log:/root/log:cached
    environment:
      POSTGRES_PASSWORD: asdjnjsd0SAD
      POSTGRES_USER: postgres
      POSTGRES_DB: aviata
    ports:
      - "5433:5432"

  redis:
    container_name: redis
    image: redis:5.0.5
    hostname: redis
    environment:
      - TZ=Asia/Almaty
    ports:
      - "127.0.0.1:6379:6379"
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes: ['./:/files']
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
      - postgres


  worker:
    restart: always
    container_name: worker
    build:
      context: .
    command: "celery -A background_jobs.taskmaster worker -l INFO -P eventlet"
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    environment:
      - TZ=Asia/Almaty

  beat:
    restart: always
    container_name: celery_beat
    build:
      context: .
    command: "celery -A background_jobs.scheduler beat -l INFO"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - worker
    environment:
      - TZ=Asia/Almaty
